# Generated by Django 5.1 on 2024-09-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="номер версии продукта", verbose_name="Номер версии"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Наименование версии продукта",
                        max_length=150,
                        verbose_name="Наименование версии",
                    ),
                ),
                (
                    "version_active",
                    models.BooleanField(default=False, verbose_name="Активная версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продукта",
                "ordering": ("version_name", "version_number"),
            },
        ),
    ]
