# Generated by Django 4.2.2 on 2024-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
    ]
